# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38614e4b8a04f4abc6c03a82aea333236b55b4cab5fd2024c5994239cb00d108d8ad42488eaec132f15cde0dcd2a2fd2ac169e1c845fabe61c87963d01797982

test:
  secret_key_base: 877e62e14dd865e4235bd52bffb377da3359da0ab176fb20c3a4274dbfa596ed74077ec50754a73f65920ccfc490e6164717df247ffddb3ef62ff505f14556ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
