# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Topic.delete_all

Topic.create([
	{title: 'Alcohol'},
	{title: 'Anger'}, 
	{title: 'Anoint'}, 
	{title: 'Beautitudes'}, 
  	{title: 'Anger'}, 
  	{title: 'Anointing'}, 
  	{title: 'Beatitudes'},
  	{title: 'Blood of Jesus'}, 
  	{title: 'Children'},
  	{title: 'Church'},	
  	{title: 'Consecration'},
	{title: 'Covenant'},	
	{title: 'Deliverance'},
	{title: 'Doubt'},
	{title: 'Drinking'},
	{title: 'Eagle'},
	{title: 'End Times'},	
	{title: 'Faith'},
	{title: 'Forgiveness'},
	{title: 'Healing'},
	{title: 'Health'},	
	{title: 'Help'},
	{title: 'Holy'},
	{title: 'Holiness'},	
	{title: 'Righteous'},
	{title: 'Righteousness'},	
	{title: 'Holy Spirit'},
	{title: 'Jesus Miracles'},	
	{title: 'Jesus Walking on Water'},
	{title: 'Kingdom of God'},	
	{title: 'Kingdom of Heaven'},
	{title: 'Knowledge'},	
	{title: 'Light'},
	{title: 'Loneliness'},
	{title: 'Lonely'},
	{title: 'Love'},
	{title: 'Lust'},	
	{title: 'Marriage'},
	{title: 'Mercy'},
	{title: 'Ministry'},	
	{title: 'Money'},
	{title: 'Peace'},
	{title: 'Parables'},	
	{title: 'Paul at Damascus'},
	{title: 'Poverty'},
	{title: 'Praise'},	
	{title: 'Prayer'},
	{title: 'Pride'},
	{title: 'Prosperity'},	
	{title: 'Road to Damascus'},
	{title: 'Paul at Damascus'},	
	{title: 'Sacrifice'},
	{title: 'Signs and Wonders'},	
	{title: 'Miracles'},
	{title: 'Strength'},	
	{title: 'Success'},
	{title: 'Supernatural'},
	{title: 'Temptation'},
	{title: 'Ten Commandments'},
	{title: 'Penticost'},	
	{title: 'Names of God'},	
	{title: 'Plagues'},
	{title: 'Rapture'},	
	{title: 'Tithe'},
	{title: 'Trouble'},	
	{title: 'Trust in God'},
	{title: 'Understanding'},	
	{title: 'Victory'},
	{title: 'Vindicate'},
	{title: 'Vision'},
	{title: 'Wisdom'},	
	{title: 'Word of God'},
	{title: 'Great Commission'}, 
	{title: 'Calvary'},
	{title: 'Death Burial and Ressurection'}, 
	{title: 'Baptism'}])